"""Add created_at field

Revision ID: 291e935a1a65
Revises: a21457f93b24
Create Date: 2025-12-08 23:00:46.405834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291e935a1a65'
down_revision = 'a21457f93b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
