"""Add Product model

Revision ID: 440be055dc6b
Revises: 72e5782e89ee
Create Date: 2025-12-08 22:39:06.042863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440be055dc6b'
down_revision = '72e5782e89ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
